"""empty message

Revision ID: 3a28357a4c7d
Revises: 45afd013a313
Create Date: 2021-07-20 14:06:50.381120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a28357a4c7d'
down_revision = '45afd013a313'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('discipline', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'discipline')
    # ### end Alembic commands ###
